//! Shortest-roundtrip `f64` → decimal-string formatter.
//!
//! Port of the teju-jagua algorithm by Cassio Neri (Apache-2.0).
//! Unlike Grisu3, teju-jagua always succeeds — no fallback path needed.
//! The algorithm decomposes an IEEE 754 double into binary fields, then
//! uses a 128-bit multiply-and-shift with precomputed tables to find the
//! shortest decimal mantissa that round-trips.
//!
//! Tables generated by `teju_gen.rs` (test-only module) and cross-validated
//! against the C reference at https://github.com/cassioneri/teju_jagua.

#![allow(
    clippy::many_single_char_names,
    clippy::unreadable_literal,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::cast_lossless,
    clippy::cast_precision_loss,
    clippy::similar_names,
    clippy::module_name_repetitions,
    clippy::missing_const_for_fn,
    clippy::doc_markdown,
    clippy::redundant_pub_crate
)]

extern crate alloc;

use alloc::string::String;
use core::fmt::{self, Write as _};

// ===========================================================================
// IEEE 754 constants and decomposition.
// ===========================================================================

const MANTISSA_WIDTH: u32 = 53;
const EXPONENT_MIN: i32 = -1074;
const HIDDEN_BIT: u64 = 1u64 << (MANTISSA_WIDTH - 1);
const SIG_MASK: u64 = HIDDEN_BIT - 1;
const EXP_SHIFT: u32 = MANTISSA_WIDTH - 1; // 52

struct BinaryF64 {
    exponent: i32,
    mantissa: u64,
}

fn decompose(value: f64) -> BinaryF64 {
    debug_assert!(value.is_finite() && value > 0.0);
    let bits = value.to_bits();
    let mut mantissa = bits & SIG_MASK;
    let biased_exp = (bits >> EXP_SHIFT) as i32;
    let mut exponent;
    if biased_exp != 0 {
        exponent = biased_exp - 1;
        mantissa |= HIDDEN_BIT;
    } else {
        exponent = 0;
    }
    exponent += EXPONENT_MIN;
    BinaryF64 { exponent, mantissa }
}

// ===========================================================================
// Algorithm helpers.
// ===========================================================================

#[inline]
fn log10_pow2(e: i32) -> i32 {
    ((1_292_913_987i64 * i64::from(e)) >> 32) as i32
}

#[inline]
fn log10_pow2_residual(e: i32) -> u32 {
    // Matches C: (uint32_t)((int64_t)1292913987u * e) / 1292913987u
    // The cast to uint32_t truncates the 64-bit product to 32 bits
    // BEFORE the unsigned division.
    let product = 1_292_913_987i64 * i64::from(e);
    (product as u32) / 1_292_913_987u32
}

#[inline]
fn mshift(m: u64, upper: u64, lower: u64) -> u64 {
    let hi = u128::from(m) * u128::from(upper);
    let lo = u128::from(m) * u128::from(lower);
    ((hi + (lo >> 64)) >> 64) as u64
}

#[inline]
fn mshift_pow2(k: u32, upper: u64, lower: u64) -> u64 {
    let s = k as i32 - 64;
    if s <= 0 {
        upper >> (-s) as u32
    } else {
        (upper << s as u32) | (lower >> (64 - s as u32))
    }
}

#[inline]
fn is_multiple_of_pow2(e: i32, n: u64) -> bool {
    debug_assert!(e >= 0 && (e as u32) < 64);
    (n >> e as u32) << e as u32 == n
}

#[inline]
fn can_test_pow5(f: i32) -> bool {
    f >= 0 && (f as usize) < MINVERSE.len()
}

#[inline]
fn is_multiple_of_pow5(f: i32, n: u64) -> bool {
    debug_assert!(can_test_pow5(f));
    let (inv, bound) = MINVERSE[f as usize];
    n.wrapping_mul(inv) <= bound
}

#[inline]
fn div10(n: u64) -> u64 {
    n / 10
}

// ===========================================================================
// Decimal result + trailing-zero removal.
// ===========================================================================

struct DecimalF64 {
    exponent: i32,
    mantissa: u64,
}

fn remove_trailing_zeros(mut m: u64, mut e: i32) -> DecimalF64 {
    let minv5: u64 = 0u64.wrapping_sub(u64::MAX / 5);
    let bound: u64 = u64::MAX / 10 + 1;
    loop {
        let q = m.wrapping_mul(minv5).rotate_right(1);
        if q >= bound {
            return DecimalF64 { exponent: e, mantissa: m };
        }
        e += 1;
        m = q;
    }
}

// ===========================================================================
// Teju Jagua core.
// ===========================================================================

const MANTISSA_UNCENTRED: u64 = 1u64 << (MANTISSA_WIDTH - 1);

#[inline]
fn is_small_integer(e: i32, m: u64) -> bool {
    let neg_e = -e;
    neg_e >= 0 && (neg_e as u32) < MANTISSA_WIDTH && is_multiple_of_pow2(neg_e, m)
}

#[inline]
fn is_centred(e: i32, m: u64) -> bool {
    m != MANTISSA_UNCENTRED || e == EXPONENT_MIN
}

fn to_decimal_small_integer(e: i32, m: u64) -> DecimalF64 {
    debug_assert!(is_small_integer(e, m));
    remove_trailing_zeros(m >> (-e) as u32, 0)
}

fn to_decimal_centred(e: i32, m: u64) -> DecimalF64 {
    debug_assert!(is_centred(e, m));

    let f = log10_pow2(e);
    let r = log10_pow2_residual(e);
    let idx = (f - STORAGE_INDEX_OFFSET) as usize;
    let (lower, upper) = MULTIPLIERS[idx];
    let m_b = (2 * m + 1) << r;
    let m_a = (2 * m - 1) << r;
    let b = mshift(m_b, upper, lower);
    let a = mshift(m_a, upper, lower);
    let q = div10(b);
    let s = 10 * q;

    if can_test_pow5(f) {
        let shortest = if s == b {
            !is_multiple_of_pow5(f, m_b) || m % 2 == 0
        } else if s == a {
            is_multiple_of_pow5(f, m_a) && m % 2 == 0
        } else {
            s > a
        };
        if shortest {
            return remove_trailing_zeros(q, f + 1);
        }
    } else if s > a {
        return remove_trailing_zeros(q, f + 1);
    }

    let m_c = (4 * m) << r;
    let c_2 = mshift(m_c, upper, lower);
    let c = c_2 / 2;
    let pick_left = (is_tie_neg_f(f, c_2) && c % 2 == 0) || c_2 % 2 == 0;
    DecimalF64 {
        exponent: f,
        mantissa: c + u64::from(!pick_left),
    }
}

fn to_decimal_uncentred(e: i32) -> DecimalF64 {
    let m = MANTISSA_UNCENTRED;
    let f = log10_pow2(e);
    let r = log10_pow2_residual(e);
    let idx = (f - STORAGE_INDEX_OFFSET) as usize;
    let (lower, upper) = MULTIPLIERS[idx];
    let m_a = (4 * m - 1) << r;
    let m_b = (2 * m + 1) << r;
    let b = mshift(m_b, upper, lower);
    let a = mshift(m_a, upper, lower) / 2;
    let q = div10(b);
    let s = 10 * q;

    if a < b {
        if can_test_pow5(f) {
            let shortest = if s == b {
                !is_tie_uncentred(f, m_b) || m % 2 == 0
            } else if s == a {
                is_tie_uncentred(f, m_a) && m % 2 == 0
            } else {
                s > a
            };
            if shortest {
                return remove_trailing_zeros(q, f + 1);
            }
        } else if s > a {
            return remove_trailing_zeros(q, f + 1);
        }

        let log2_m_c = MANTISSA_WIDTH + r + 1;
        let c_2 = mshift_pow2(log2_m_c, upper, lower);
        let c = c_2 / 2;

        if c == a && !is_tie_uncentred(f, m_a) {
            return DecimalF64 { exponent: f, mantissa: c + 1 };
        }

        let pick_left = (is_tie_neg_f(f, c_2) && c % 2 == 0) || c_2 % 2 == 0;
        return DecimalF64 {
            exponent: f,
            mantissa: c + u64::from(!pick_left),
        };
    }

    if is_tie_uncentred(f, m_a) && m % 2 == 0 {
        return remove_trailing_zeros(a, f);
    }

    let m_c = (40 * m) << r;
    let c_2 = mshift(m_c, upper, lower);
    let c = c_2 / 2;
    let pick_left = (is_tie_neg_f(f, c_2) && c % 2 == 0) || c_2 % 2 == 0;
    DecimalF64 {
        exponent: f - 1,
        mantissa: c + u64::from(!pick_left),
    }
}

#[inline]
fn is_tie_neg_f(f: i32, c_2: u64) -> bool {
    can_test_pow5(-f) && is_multiple_of_pow5(-f, c_2)
}

#[inline]
fn is_tie_uncentred(f: i32, m: u64) -> bool {
    m % 5 == 0 && can_test_pow5(f) && is_multiple_of_pow5(f, m)
}

fn teju(value: f64) -> DecimalF64 {
    let b = decompose(value);
    let e = b.exponent;
    let m = b.mantissa;

    if is_small_integer(e, m) {
        return to_decimal_small_integer(e, m);
    }
    if is_centred(e, m) {
        return to_decimal_centred(e, m);
    }
    to_decimal_uncentred(e)
}

// ===========================================================================
// Decimal-to-string formatting.
// ===========================================================================

fn render_mantissa(mut n: u64, buf: &mut [u8; 20]) -> usize {
    if n == 0 {
        buf[0] = b'0';
        return 1;
    }
    let mut pos = 20usize;
    while n >= 100 {
        let r = (n % 100) as usize;
        n /= 100;
        pos -= 2;
        buf[pos] = DIGIT_LUT[r * 2];
        buf[pos + 1] = DIGIT_LUT[r * 2 + 1];
    }
    if n >= 10 {
        let r = n as usize;
        pos -= 2;
        buf[pos] = DIGIT_LUT[r * 2];
        buf[pos + 1] = DIGIT_LUT[r * 2 + 1];
    } else {
        pos -= 1;
        buf[pos] = b'0' + n as u8;
    }
    let len = 20 - pos;
    buf.copy_within(pos..20, 0);
    len
}

const DIGIT_LUT: &[u8; 200] = b"\
0001020304050607080910111213141516171819\
2021222324252627282930313233343536373839\
4041424344454647484950515253545556575859\
6061626364656667686970717273747576777879\
8081828384858687888990919293949596979899";

fn write_decimal(d: &DecimalF64, negative: bool, out: &mut String) {
    let mut buf = [0u8; 20];
    let len = render_mantissa(d.mantissa, &mut buf);
    #[allow(unsafe_code)]
    let digits: &str = unsafe { core::str::from_utf8_unchecked(&buf[..len]) };

    if negative {
        out.push('-');
    }
    let point = len as i32 + d.exponent;
    if (-6..=21).contains(&point) {
        if point <= 0 {
            out.push_str("0.");
            push_zeros(out, -point as usize);
            out.push_str(digits);
        } else if (point as usize) >= digits.len() {
            out.push_str(digits);
            push_zeros(out, point as usize - digits.len());
            out.push_str(".0");
        } else {
            let p = point as usize;
            out.push_str(&digits[..p]);
            out.push('.');
            out.push_str(&digits[p..]);
        }
    } else {
        out.push_str(&digits[..1]);
        if len > 1 {
            out.push('.');
            out.push_str(&digits[1..]);
        }
        out.push('e');
        let exp = point - 1;
        let _ = write!(out, "{exp}");
    }
}

fn push_zeros(out: &mut String, n: usize) {
    const ZEROS: &str = "00000000000000000000000";
    debug_assert!(n <= ZEROS.len());
    out.push_str(&ZEROS[..n]);
}

// ===========================================================================
// Public API — unchanged signatures from the Grisu3 era.
// ===========================================================================

pub(crate) fn format_finite(f: f64, out: &mut String) {
    if f == 0.0 {
        if f.is_sign_negative() {
            out.push_str("-0.0");
        } else {
            out.push_str("0.0");
        }
        return;
    }
    let negative = f.is_sign_negative();
    let d = teju(f.abs());
    write_decimal(&d, negative, out);
}

pub(crate) fn format_finite_fmt<W: fmt::Write + ?Sized>(f: f64, out: &mut W) -> fmt::Result {
    if f == 0.0 {
        return out.write_str(if f.is_sign_negative() { "-0.0" } else { "0.0" });
    }
    let negative = f.is_sign_negative();
    let d = teju(f.abs());
    let mut buf = String::with_capacity(32);
    write_decimal(&d, negative, &mut buf);
    out.write_str(&buf)
}

// ===========================================================================
// Tables — generated by teju_gen.rs, cross-validated against C reference.
// ===========================================================================

const STORAGE_INDEX_OFFSET: i32 = -324;

include!("teju_tables.txt");

// ===========================================================================
// Tests.
// ===========================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::format;
    use alloc::string::String;

    #[test]
    #[allow(clippy::float_cmp)]
    fn teju_output_roundtrips() {
        let mut state: u64 = 0xCAFE_BABE_DEAD_BEEF;
        let mut count = 0usize;
        for _ in 0..10_000 {
            state = state
                .wrapping_mul(6_364_136_223_846_793_005)
                .wrapping_add(1_442_695_040_888_963_407);
            let mantissa = (state >> 11) as f64 / (1u64 << 53) as f64;
            let signed = mantissa.mul_add(2.0, -1.0);
            let v = match count % 10 {
                0 => signed * 1e-6,
                1 => signed * 1e6,
                _ => signed * 100.0,
            };
            count += 1;
            if !v.is_finite() || v == 0.0 {
                continue;
            }
            let mut out = String::new();
            format_finite(v, &mut out);
            let parsed: f64 = out.parse().expect("our output parses");
            assert_eq!(
                parsed, v,
                "roundtrip failed: formatted={out:?} for v={v:e} (bits=0x{:016x})",
                v.to_bits()
            );
        }
    }

    #[test]
    #[allow(clippy::float_cmp, clippy::approx_constant)]
    fn teju_matches_libstd_display() {
        let cases = [
            1.0_f64, 1.5, 0.1, 0.2, 0.3, 100.0, 12.5, 1.5e10, -2.7e-5,
            3.14159, 1e100, 1e-100, 1.7976931348623157e308, 5e-324,
        ];
        for &v in &cases {
            if v == 0.0 || !v.is_finite() {
                continue;
            }
            let mut ours = String::new();
            format_finite(v, &mut ours);
            let libstd = format!("{v}");
            let ours_parsed: f64 = ours.parse().expect("ours parses");
            let libstd_parsed: f64 = libstd.parse().expect("libstd parses");
            assert_eq!(
                ours_parsed, libstd_parsed,
                "ours={ours:?} libstd={libstd:?} for v={v:e}",
            );
        }
    }

    #[test]
    fn teju_edge_cases() {
        let cases: &[(f64, &str)] = &[
            (1.0, "1.0"),
            (2.0, "2.0"),
            (0.5, "0.5"),
            (10.0, "10.0"),
            (100.0, "100.0"),
            (1e20, "100000000000000000000.0"),
            (1.5, "1.5"),
        ];
        for &(v, expected) in cases {
            let mut out = String::new();
            format_finite(v, &mut out);
            assert_eq!(out, expected, "for {v}");
        }
    }

    #[test]
    fn teju_zero_handling() {
        let mut pos = String::new();
        format_finite(0.0, &mut pos);
        assert_eq!(pos, "0.0");

        let mut neg = String::new();
        format_finite(-0.0, &mut neg);
        assert_eq!(neg, "-0.0");
    }

    #[test]
    fn teju_small_integers() {
        for i in 1u64..=1000 {
            let v = i as f64;
            let d = teju(v);
            let reconstructed = d.mantissa as f64 * 10f64.powi(d.exponent);
            assert_eq!(
                reconstructed, v,
                "small integer {i}: mantissa={}, exp={}",
                d.mantissa, d.exponent
            );
        }
    }
}
